export interface InitialRecording {
  id: string;
  created_at: string;
  duration: number;
  audio_file_path: string;
  transcript: string;
  summary: string;
  status: "completed" | "processing" | "failed_transcription" | "failed_summary";
  error_message?: string | null;
}

export const INITIAL_RECORDINGS: InitialRecording[] = [
  {
    "id": "rec_1791362193481_n2hdi",
    "created_at": "2026-10-07T08:36:33.508Z",
    "duration": 84,
    "audio_file_path": "rec_1791362193481_n2hdi.webm",
    "transcript": "Speaker 1: Hello.\nSpeaker 2: Hello.\nSpeaker 2: Good afternoon, Reshma sir.\nSpeaker 1: Haan ji, kaun bol raha hai?\nSpeaker 2: Sir, main Riya baat kar rahi hoon Shubh Sanjivani Virar West se.\nSpeaker 1: Haan ji, boliye.\nSpeaker 2: Sir, aapki inquiry aayi thi mujhe property konse, to main janna chahti hoon kya dekh rahe hain, 1 BHK, 2 BHK?\nSpeaker 2: Main na Jodi flats dekh raha tha.\nSpeaker 1: Okay sir, hamare paas unlimitable hai.\nSpeaker 1: Waise aap kahan pe rehte hain?\nSpeaker 2: Main Mumbai mein rehta hoon, \nSpeaker 2: Okay sir, to sir site visit ke liye kabhi aa sakte hain?\nSpeaker 2: Ma'am, mujhe locations ke bare mein zara bataoge, ki kitna dur hai budget?\nSpeaker 2: Sir, hamara G plus 23 storey ki building hai.\nSpeaker 1: Haan ji.\nSpeaker 2: Main amenities pucha hoon ma'am.\nSpeaker 2: Sir aap visit ke liye kab aaoge?\nSpeaker 1: Ma'am main location ke bare mein puch raha hoon, aap amenities ke bare mein bata rahe ho, location nahi bata pa rahe ho.\nSpeaker 2: Sir, yeh Virar West mein hai, Vaikunth Nagar mein.\nSpeaker 1: Haan ji.\nSpeaker 2: Ji, \nSpeaker 2: Project se station kitna dur hai?\nSpeaker 2: Sir, waise aap kya dekh rahe ho, 1 BHK, 2 BHK?\nSpeaker 1: Ma'am, maine bataya na Jodi flat dekh raha hoon main.\nSpeaker 2: Okay, waise aap investment ke liye dekh rahe ho personal use ke liye?\nSpeaker 1: Ma'am, main jab tabhi bataunga jab aap mujhe sab properly details bataoge, pricing kya hai, mere ko\nSpeaker 2: Sir, aap visit ke liye toh aaiye, toh main aapko sales person aapko explain kar degi.\nSpeaker 2: Okay.\nSpeaker 2: Aur station se kitna dur hai ma'am?\nSpeaker 2: Sir, aap visit ke liye toh aaiye, aapko yahan pe sales person explain kar denge.",
    "summary": "{\"overall_summary\":\"The sales representative called the client to follow up on a property inquiry for Shubh Sanjivani in Virar West. The conversation lacked effective communication as the representative repeatedly pushed for a site visit instead of answering the client's specific questions regarding location, pricing, and distance to the railway station, leading to frustration from the client.\",\"key_discussion_points\":[\"The client inquired about Jodi flats and asked for project details including location, budget, and distance from the railway station.\",\"The representative stated the project is a G plus 23-story building located in Vaikunth Nagar, Virar West.\",\"The client expressed frustration because the representative repeatedly deflected questions about location and pricing by insisting on a site visit instead of providing proper details.\"],\"pitch_score\":3,\"pitch_percentage\":30}",
    "status": "completed",
    "error_message": null
  },
  {
    "id": "rec_1791361919298_hzsym",
    "created_at": "2026-10-07T08:31:59.325Z",
    "duration": 157,
    "audio_file_path": "rec_1791361919298_hzsym.webm",
    "transcript": "Speaker 1: Hello.\nSpeaker 2: Haan ji.\nSpeaker 1: Kon?\nSpeaker 2: Main baat kar rahi hun shilpa shanti vihar se ye sabse aise baat ho rahi hai.\nSpeaker 1: Haan ji baat ho rahi hai but ye shilpa shanti kya hai?\nSpeaker 2: Ye project ka naam hai sir hamare.\nSpeaker 1: Kaunsa project ka naam hai?\nSpeaker 1: Ye main kaise bataunga sir?\nSpeaker 1: Hello.\nSpeaker 2: Hello.\nSpeaker 2: Good afternoon Risat sir.\nSpeaker 1: Haan ji boliye.\nSpeaker 2: Sir main riya baat kar rahi hun shilpa shanti vihar se.\nSpeaker 1: Haan ji.\nSpeaker 2: Sir aap ki enquiry receive hui thi ki mujhe property kon si iske liye to main jaan sakti hu kya dekh rahe hai?\nSpeaker 1: Property purchase maine kuch enquiry nahi kiya tha.\nSpeaker 2: Nahi sir hamare system me to show ho raha hai.\nSpeaker 1: Aapne nahi kiya hoga but aapke family me kisi ne kiya hoga.\nSpeaker 1: Nahi ekdam mere siva aur koi nahi hai. Single hun.\nSpeaker 1: Sir aapne aapne message se kar diya hoga.\nSpeaker 2: Okay.\nSpeaker 2: Bataiye kya hai?\nSpeaker 2: To agar in future aap search karenge to aap kya dekhenge sir one BHK ya two BHK?\nSpeaker 1: Waise to mera property lene ka kuch plan nahi hai but aap kya offer kar rahe hai?\nSpeaker 2: Sir hamare paas na one BHK me do carpet area hai.\nSpeaker 1: Okay.\nSpeaker 2: Ek 149 ka aur ek 491 ka hai.\nSpeaker 1: Okay.\nSpeaker 2: G plus 23 story ki building hai aur ye Virar West, Vikhinagar me located hai.\nSpeaker 2: Jisme aapko 15 plus amenities mil jate hai.\nSpeaker 1: To ye under construction hai ki ready to move hai?\nSpeaker 2: Under construction project hai sir hamara jisme 90 plus kaam ho chuka hai.\nSpeaker 2: Aur abhi hamara offer bhi chal raha hai 50-50 payment plan ka.\nSpeaker 1: Ji.\nSpeaker 2: Station se kitna dur hai?\nSpeaker 2: Station se sir walking distance 10 minute ka hai.\nSpeaker 1: Okay.\nSpeaker 2: Waise aap kahan pe rehte ho?\nSpeaker 1: Main to Andheri kehta hun main.\nSpeaker 2: Okay to ye investment ke liye dekh rahe ho sir ya personal use ke liye?\nSpeaker 1: Main to fir bol raha main abhi ke liye main dekh nahi raha hun.\nSpeaker 2: Agar in future aap dekhenge to sir?\nSpeaker 1: Main bataunga.\nSpeaker 1: Ye to main filhal dekh nahi raha hun.\nSpeaker 2: Okay sir chalega but aap ek baar kabhi Virar aayenge na to hamara project visit kijiye hamara actual flat bhi ready hai.\nSpeaker 1: Kya hai projects ke bare me location me kya kya hai?\nSpeaker 2: Connectivity me dekhna chahe to near aapko walking distance two minute me hamara Reliance mall hai.\nSpeaker 2: Starbucks hai.\nSpeaker 2: Aur fir near by aapko \nSpeaker 2: Okay mam theek hai main baad me baat karta hun.\nSpeaker 1: Mujhe lagta hai aapko itna thoda sa knowledge nahi hai aap apna knowledge le lijiye.\nSpeaker 1: To main aapko baad me baat karta hun.",
    "summary": "{\"overall_summary\":\"The sales representative called the client regarding a property inquiry for the Shilpa Shanti Vihar project in Virar West, though the client stated he did not make any enquiry. The representative discussed project details, configuration, amenities, and location, while the client remained uncommitted and ultimately ended the call after questioning the representative's knowledge.\",\"key_discussion_points\":[\"Project name and location: Shilpa Shanti Vihar in Virar West, Vikhinagar, with a G plus 23 storeys building structure.\",\"Property configuration and status: 1 BHK units with carpet areas of 149 and 491 sq ft, under construction with 90 percent work completed.\",\"Pricing and payment plans: A 50-50 payment plan offer is currently running.\",\"Accessibility and distance from station: Approximately 10 minutes walking distance from the station, with nearby amenities like Reliance Mall and Starbucks.\",\"Client's intent: The client stated he currently has no immediate plan to purchase or look for property, and questioned the representative's product knowledge.\"],\"pitch_score\":5,\"pitch_percentage\":50}",
    "status": "completed",
    "error_message": null
  },
  {
    "id": "rec_1791361313796_8oxzy",
    "created_at": "2026-10-07T08:21:53.811Z",
    "duration": 36,
    "audio_file_path": "rec_1791361313796_8oxzy.webm",
    "transcript": "Speaker 1: Hello.\nSpeaker 2: Hello.\nSpeaker 1: Hello, Mr. Rishabh? Haan ji, boliye.\nSpeaker 2: Very good afternoon, sir. Main Varun baat kar raha hoon Sripal Signature Builder office, Virar se. Haan ji, boliye.\nSpeaker 1: Actually, sir, aapki inquiry generate hui thi, EMI property ke regarding. Aap property dekh rahe ho purchase ke liye?\nSpeaker 2: Nahi, maine toh koi inquiry nahi kiya hai, aur na hi main koi property dekh raha hoon.\nSpeaker 1: Theek hai, sir, but hamare system mein dikha raha hai ki inquiry receive hui hai, toh it might be possible ki aapke family member mein se kisi ne ki ho?\nSpeaker 2: Nahi, mera koi family member hi nahi hai, sir.\nSpeaker 1: Theek hai, sir, no problem. But, if future mein koi property dekhoge, toh kya main do minute apne project ke baare mein aapko samjha sakta hoon?\nSpeaker 2: Nahi, nahi, interest nahi hai.",
    "summary": "{\"overall_summary\":\"The salesperson contacted the client regarding a real estate inquiry for an EMI property, but the client stated that neither he nor any family member had made an inquiry or was looking to purchase property. The call ended quickly with the client expressing no interest.\",\"key_discussion_points\":[\"Salesperson reached out regarding a property inquiry generated in their system for Sripal Signature Builder in Virar.\",\"Client denied making any property inquiry or looking to purchase property.\",\"Client stated he has no family members who would have made the inquiry.\",\"Salesperson offered to pitch the project for the future, but the client declined, stating he has no interest.\"],\"pitch_score\":6,\"pitch_percentage\":60}",
    "status": "completed",
    "error_message": null
  },
  {
    "id": "rec_1791354066493_mtc8n",
    "created_at": "2026-10-07T06:21:06.507Z",
    "duration": 86,
    "audio_file_path": "rec_1791354066493_mtc8n.webm",
    "transcript": "Speaker 1: क्या करना है?\nSpeaker 1: वही वाला ना जिसमें प्रॉपर्टी है।\nSpeaker 2: हेलो\nSpeaker 1: हेलो\nSpeaker 2: गुड आफ्टरनून सर मैं रिया बात कर रही हूं श्रीमा शांति विरान वेस्ट से।\nSpeaker 1: हां बोलो।\nSpeaker 2: सर आपकी इंक्वायरी ऐसे हुई थी मुझे प्रॉपर्टी परचेस के लिए तो मैं जान सकती हूं क्या देख रहे हो 1 बीएचके 2 बीएचके?\nSpeaker 1: नहीं मैंने तो कोई इंक्वायरी नहीं की।\nSpeaker 2: सर हमारे सिस्टम में शो हो रहा है आपकी इंक्वायरी।\nSpeaker 1: अच्छा लेकिन मैंने तो की नहीं है।\nSpeaker 2: आपकी फैमिली या कोई फ्रेंड सर्कल में किया होगा सर।\nSpeaker 1: किया हो सकता है बताओ।\nSpeaker 2: तो आप क्या देख रहे हैं अगर इन फ्यूचर आप सर्च करना चाहेंगे तो आ रहा है।\nSpeaker 1: 2 बीएचके देख रहा हूं।\nSpeaker 2: सर हमारे पास 2 बीएचके में दो कारपेट एरिया है। एक 66 676 का एक 672 का है।\nSpeaker 1: अच्छा तो क्या प्राइस रहेगा?\nSpeaker 2: ये सर 67 लाख ऑनवर्ड्स जाता है।\nSpeaker 1: एमेनिटीज क्या-क्या है?\nSpeaker 2: एमेनिटीज सर हमारे पास 15 प्लस एमेनिटीज है जिसमें किड्स प्ले एरिया सीनियर सीनियर सिटीजन एरिया और मल्टीपल है सर हमारे पास।\nSpeaker 1: और कब तक मिलेगा मेरे को प्रोजेक्ट?\nSpeaker 2: अह छह से आठ मंथ का पजेशन है सर उसका।\nSpeaker 1: मेरे को जल्दी चाहिए था थोड़ा।\nSpeaker 2: पॉसिबल नहीं है सर उतना तो।\nSpeaker 1: अच्छा ठीक है।\nSpeaker 2: वैसे रहने के लिए कहां पे हो?\nSpeaker 1: मैं सांता क्रूज में रहता हूं अभी इन्वेस्टमेंट के लिए सोच रहा था कि देख रहा हूं।\nSpeaker 2: ओके सर चलेगा।\nSpeaker 1: तो फ्यूचर कुछ है कि नहीं वहां पे इन्वेस्ट करना चाहिए या नहीं मुझे विरार में?\nSpeaker 2: देख लो सर।\nSpeaker 1: अच्छा ठीक है आप नहीं बता पाओगे क्या?\nSpeaker 2: नहीं।\nSpeaker 1: ठीक है कोई बात नहीं देखता हूं मैं विजिट।",
    "summary": "{\"overall_summary\":\"A sales representative from Shreema Shanti Virar West contacted a client who had an inquiry regarding property purchase, though the client initially stated he did not make the inquiry. The conversation progressed to discuss 2 BHK properties, pricing starting at 67 lakhs, amenities, and a possession timeline of 6 to 8 months, with the client ultimately mentioning he is looking for investment purposes from Santa Cruz.\",\"key_discussion_points\":[\"Client stated he did not personally make the property inquiry, but acknowledged someone from his family or friend circle might have.\",\"Client is looking for a 2 BHK property for investment purposes.\",\"Sales representative shared 2 BHK carpet area options of 676 and 672 sq. ft. starting at 67 lakhs onwards.\",\"Project includes over 15 amenities such as a kids' play area and senior citizen area.\",\"Possession timeline is 6 to 8 months, which the client found a bit too late as he wanted it sooner.\",\"Client currently lives in Santa Cruz and asked about the investment potential in Virar, to which the representative was unable to provide a detailed answer.\"],\"pitch_score\":4,\"pitch_percentage\":40}",
    "status": "completed",
    "error_message": null
  },
  {
    "id": "rec_1791353909135_h7fvh",
    "created_at": "2026-10-07T06:18:29.153Z",
    "duration": 105,
    "audio_file_path": "rec_1791353909135_h7fvh.webm",
    "transcript": "Speaker 1: Hello. Good afternoon. Sir, boliye.\nSpeaker 2: Sir, main yeh baat karu Shripa Shanti Vihar West se.\nSpeaker 1: Sir, aapki enquiry aayi hui thi mujhe property purchase ke liye to main jaan sakti hu aap kya dekh rahe ho, 1 BHK, 2 BHK?\nSpeaker 2: I'm talking about 2 BHK.\nSpeaker 1: Okay, sir. 1 BHK mein hamare paas do carpet area hai, ek 476 ka aur ek 491 ka.\nSpeaker 2: Ji, sir yeh G plus 23 storey ki building hai. Yeh Vihar West, Vihar Nagar mein located hai.\nSpeaker 1: Toh carpet area kya bataya?\nSpeaker 2: Ek 476 ka hai, ek 491 ka hai.\nSpeaker 1: Price kya banega?\nSpeaker 2: Starting sir, 45 lakh onwards hai.\nSpeaker 1: 470?\nSpeaker 2: 476 ka hai aur?\nSpeaker 1: 491 ka hai.\nSpeaker 2: 476 ka kya price hai?\nSpeaker 1: 45 lakh onwards hai, sir.\nSpeaker 2: Onwards hai, exact nahi bata sakte aap?\nSpeaker 1: Nahi, sir yeh hume allow nahi hai, main caller team se hu. Aap yahan pe aayenge na toh hamare sales person aapko explain kar denge.\nSpeaker 2: Kahan pe hai aapka project?\nSpeaker 1: Yeh Vihar Nagar mein hai, sir, Vihar West mein.\nSpeaker 2: Ji. Waise aap kahan pe rehte ho?\nSpeaker 1: Main toh abhi Andheri mein rehta hu.\nSpeaker 2: Okay.\nSpeaker 1: Toh sir, aapko site visit ke liye kab possible hoga?\nSpeaker 2: Abhi toh time nahi hai mere paas, filhaal. Aap batao na pehle project ke bare mein amenities kya-kya hai?\nSpeaker 1: Sir, aapko isme na 50 plus amenities mil jaate hai, jaise kids play area, senior citizen area.\nSpeaker 2: Achcha.\nSpeaker 1: Yes, sir. Aur multiple option hai, sir, hamare paas amenities mein.\nSpeaker 2: Possession kab tak milega?\nSpeaker 1: Yeh chhe se aath month mein possession mil raha hai, sir.\nSpeaker 2: Achcha, aur late hua toh?\nSpeaker 1: Nahi, sir. Humne bahut saare projects hamare possession se pehle kiye hai deliver.",
    "summary": "{\"overall_summary\":\"The sales caller contacted a client who had inquired about purchasing a property in Shripa Shanti Vihar West. They discussed 2 BHK configurations, pricing starting from 45 lakhs onwards, project location, 50 plus amenities, and an expected possession timeline of six to eight months.\",\"key_discussion_points\":[\"Property configuration of 2 BHK with carpet areas of 476 and 491 square feet\",\"Starting price of 45 lakhs onwards\",\"Project location in Vihar Nagar, Vihar West, featuring a G plus 23 storey building\",\"Inclusion of over 50 amenities such as kids play area and senior citizen area\",\"Possession timeline of 6 to 8 months\"],\"pitch_score\":7,\"pitch_percentage\":70}",
    "status": "completed",
    "error_message": null
  },
  {
    "id": "rec_1791291355543_pquwj",
    "created_at": "2026-10-06T13:05:55.543Z",
    "duration": 120,
    "audio_file_path": "rec_1788863273211_di3zj.webm",
    "transcript": "Sales Rep: Hello sir, good evening. Calling from Shripal Shanti customer desk.\nClient: Yes, please tell me.\nSales Rep: Sir, you had inquired about our 2 BHK premium residential flats in Virar.\nClient: Yes, I am looking for a 2 BHK around 60 to 70 lakhs budget with parking.\nSales Rep: Absolutely sir. We have 2 BHK master configurations starting from 62 lakhs with carpet area of 645 sq. ft., including reserved covered car parking.\nClient: When can we visit the site?\nSales Rep: Sir, we are open all seven days. We can arrange a site pickup for you this Saturday.\nClient: Great, please share the location and brochure on WhatsApp, I will confirm the time.\nSales Rep: Sure sir, sending details right away. Thank you!",
    "summary": "{\"pitch_score\":8,\"pitch_percentage\":80,\"overall_summary\":\"Comprehensive sales call presenting 2 BHK residential configurations at Virar with pricing between 60 to 70 lakhs. Client requested brochure on WhatsApp and agreed to schedule a weekend site visit.\",\"key_discussion_points\":[\"Client seeking 2 BHK flat within 60-70 Lakhs budget with reserved parking.\",\"Sales rep explained 645 sq. ft. master layout starting at 62 Lakhs.\",\"Pickup service offered for upcoming weekend site visit.\"],\"client_requirements\":[\"2 BHK Configuration\",\"Budget 60-70 Lakhs\",\"Reserved Car Parking\"],\"important_questions_concerns\":[\"Site visit timing and location details\"],\"action_items\":[\"Send digital brochure and Google Map location on WhatsApp\"],\"next_steps\":[\"Confirm Saturday site visit timing with client\"]}",
    "status": "completed",
    "error_message": null
  },
  {
    "id": "rec_1791291001140_gr2mr",
    "created_at": "2026-10-06T13:01:01.140Z",
    "duration": 5,
    "audio_file_path": "rec_1788862633941_smjxt.webm",
    "transcript": "Client: Hello?\nSales Rep: Good evening sir, calling from sales team.\nClient: I am driving right now. Please call back tomorrow morning.\nSales Rep: Sure sir, will call you at 11 AM.",
    "summary": "{\"pitch_score\":7,\"pitch_percentage\":70,\"overall_summary\":\"Brief outreach call. Client was driving and requested a morning callback at 11:00 AM.\",\"key_discussion_points\":[\"Client currently occupied while driving.\",\"Agreed callback scheduled for tomorrow at 11:00 AM.\"],\"client_requirements\":[\"Not mentioned\"],\"important_questions_concerns\":[\"Client unavailable at time of call\"],\"action_items\":[\"Set CRM task for follow-up tomorrow at 11:00 AM\"],\"next_steps\":[\"Call client tomorrow morning\"]}",
    "status": "completed",
    "error_message": null
  },
  {
    "id": "rec_1791290588438_7knym",
    "created_at": "2026-10-06T12:53:08.438Z",
    "duration": 96,
    "audio_file_path": "rec_1788862633941_smjxt.webm",
    "transcript": "Sales Rep: Hello ma'am, Shripal sales office here. Regarding your inquiry on commercial and residential units.\nClient: Actually I wanted ready possession shops, do you have commercial shops ready?\nSales Rep: Commercial shops are in the under-construction tower, possession is after 14 months.\nClient: No, I need immediate possession for business setup.\nSales Rep: Okay ma'am, I will check if any resale or investor unit is available and update you.\nClient: Okay, update me if ready unit is there.",
    "summary": "{\"pitch_score\":5,\"pitch_percentage\":50,\"overall_summary\":\"Client inquired about commercial shop units with ready possession. Since current project shops have 14 months remaining, sales representative will verify available investor units.\",\"key_discussion_points\":[\"Client requirement is urgent ready-possession shop for business setup.\",\"Current project inventory has 14-month construction possession timeline.\",\"Sales rep offered to check secondary/investor ready units.\"],\"client_requirements\":[\"Commercial retail shop\",\"Immediate ready possession\"],\"important_questions_concerns\":[\"Project possession delay does not match client urgent timeline\"],\"action_items\":[\"Check internal resale inventory for immediate possession options\"],\"next_steps\":[\"Contact client if ready commercial unit becomes available\"]}",
    "status": "completed",
    "error_message": null
  },
  {
    "id": "rec_1788863273211_di3zj",
    "created_at": "2026-09-08T10:27:53.224Z",
    "duration": 105,
    "audio_file_path": "rec_1788863273211_di3zj.webm",
    "transcript": "Client: Hello.\nSales Person: Hello. Good afternoon, ma'am.\nClient: Good afternoon.\nSales Person: Ma'am, is Srishti Vats from Shripal Shanti here?\nClient: Yes.\nSales Person: Ma'am, aapki inquiry receive hui thi Shripal Shanti mein property purchase karne ka plan kar rahe ho?\nClient: Ah, ha.\nSales Person: Kya dekh rahe ho ma'am, aise? Aur kya aapke paas options hain?\nClient: One BHK, two BHK, dono options hain ma'am. Aap kya dekh rahe ho?\nSales Person: Um, actually main three BHK dekh rahi hoon. Aisa kuch option hai aapke paas?\nClient: Aur three BHK ma'am, hamare paas Jodi options aapko mil jayenge.\nSales Person: Okay, great.\nSales Person: Ma'am, aap kahan rehte ho?\nClient: Main Virar mein rehti hoon, Ekta mein.\nSales Person: Okay, toh ye aapke paas hi ma'am, aap Vaikenagar location pe hamara project hai. Tanjali Road pe aapko idea hoga.\nClient: Ha, ha, idea toh hai.\nSales Person: Toh ma'am, ye directly builder office se stand hoti hai na?\nClient: Ha, builder office se baat kar rahi hoon ma'am main.\nSales Person: Achcha, theek hai.\nSales Person: Toh abhi under construction hai ma'am, 20 slab tak ready ho chuka hai.\nClient: Hmm.\nSales Person: Aapko next year June-July tak possession mil jayega.\nClient: Okay.\nSales Person: Toh abhi plan kar rahe ho na visit ke liye, aaj possible hai kya?\nClient: Aaj toh possible nahi hai, main aapko Sunday ko batati hoon.\nSales Person: Okay, chalega ma'am. Apna seven days office chalu rehta hai.\nClient: Hmm.\nSales Person: Kabhi bhi aap aao, direct aana ma'am. Main builder office se baat kar rahi hoon.\nClient: Hmm.\nSales Person: Usme kya aapko pricing benefit milta hai.\nClient: Arre, mereko na ek CP ne bhi approach kiya tha. Matlab aapke project ke liye approach kiya tha.\nSales Person: Ma'am, woh channel partners rehte hain hamare.\nClient: Ha.\nSales Person: But main direct builder office se baat kar rahi hoon. Aap mera number save kar lijiye.\nClient: Hmm.\nSales Person: Jab bhi aayenge toh mujhe call kar dijiyega. Hamara pickup bhi rehta hai, main car bhi bhej dunga Ekta ki building ke paas.\nClient: Okay. But agar main CP ke saath aaungi toh koi dikkat hai kya?\nSales Person: Wohi mujhe dikha rahe the.\nClient: Hmm.\nSales Person: Direct aayenge toh ma'am, main aapko discount karke de sakti hoon.\nClient: On table.\nSales Person: Aap direct aaoge toh.\nClient: Achcha, matlab CP ke saath aate hain toh matlab mujhe CP ko pay karna padega, aisa?\nSales Person: Hmm.\nClient: Theek hai.\nSales Person: Theek hai.",
    "summary": "{\"pitch_score\":9,\"pitch_percentage\":90,\"overall_summary\":\"This meeting was a follow-up sales call from Shripal Shanti builder office to a client inquiring about purchasing property in Virar. The discussion covered available configurations (1 BHK, 2 BHK, and Jodi 3 BHK options), construction status (20 slabs ready), and the benefits of direct visits without channel partners.\",\"key_discussion_points\":[\"Client interested in property purchase, looking for 3 BHK Jodi options in Virar (Ekta area).\",\"Project location at Vaikenagar, Tanjali Road; 20 slabs ready with possession expected next year June-July.\",\"Sales representative offered car pickup service from Ekta building and on-table discount for direct builder visits.\",\"Client to confirm site visit on Sunday.\"]}",
    "status": "completed",
    "error_message": null
  },
  {
    "id": "rec_1788862633941_smjxt",
    "created_at": "2026-09-08T10:17:13.947Z",
    "duration": 65,
    "audio_file_path": "rec_1788862633941_smjxt.webm",
    "transcript": "Speaker 1: Hello everyone. Today we are analyzing why sales have dropped this quarter.\nSpeaker 2: Yes, looking at the data, lead response time increased from 5 minutes to 45 minutes.\nSpeaker 1: That is critical. We need to implement automated lead routing immediately.",
    "summary": "{\"pitch_score\":8.2,\"pitch_percentage\":82,\"overall_summary\":\"The meeting focused on analyzing sales performance and addressing the recent decline in conversion rates.\",\"key_discussion_points\":[\"Analysis of quarterly sales drop and response time delay from 5 to 45 minutes.\",\"Agreement to implement automated lead routing immediately.\"]}",
    "status": "completed",
    "error_message": null
  }
];
